# Generated by Django 2.1.7 on 2019-05-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiTiempo', '0003_auto_20190511_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='seleccionado',
            new_name='puntuacion',
        ),
    ]
